services:
  bearlytics:
    image: ghcr.io/hermanmartinus/bearlytics:latest
    ports:
    - 8080:8080
    volumes:
    - ./analytics:/app/data
    environment:
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-https://www.ikka.cloud,http://localhost}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-www.ikka.cloud,localhost}
      DB_PATH: ${DB_PATH:-/app/data/analytics.db}
      DEBUG: False
      SALT_SECRET: ${SALT_SECRET:?err}
      SECRET_KEY: ${SECRET_KEY:?err}
      UID: 1000
      GID: 1000
    restart: unless-stopped

